package tests;

import java.io.FileNotFoundException;
import org.apache.logging.log4j.*;
import java.io.FileReader;
import java.io.IOException;
import java.util.List;

//Generated by Selenium IDE
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.internal.TextListener;
import org.junit.runner.JUnitCore;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;

import pages.ContactUsPage;

/*import org.apache.log4j.FileAppender;
import org.apache.log4j.Layout;
import org.apache.log4j.Level;
import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;
import org.apache.log4j.SimpleLayout;*/

public class ContactUsTests {
	private static WebDriver driver;
	//private Map<String, Object> vars;
	private JSONArray users;
	Logger logger=LogManager.getLogger(ContactUsTests.class);

	JavascriptExecutor js;

	@Before

	public void setUp() throws IOException {
		driver = BaseTestClass.initializeDriver();
		js = (JavascriptExecutor) driver;
		//vars = new HashMap<String, Object>();

		try {
			JSONParser jsonParser = new JSONParser();
			FileReader reader;
			reader = new FileReader("ContactUsUsers.json");
			// Read JSON file
			users = (JSONArray) jsonParser.parse(reader);
		} catch (/*FileNotFoundException |*/ ParseException e) {
			e.printStackTrace();
		}

	}

	public static void printMethodName() {
		System.out.println("Starting " + Thread.currentThread().getStackTrace()[2].getMethodName());
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void SuccessfulMessageSent() throws InterruptedException {
		printMethodName();
		for (int i = 0; i < users.size(); i++) {
			JSONObject obj = (JSONObject) users.get(i);
			driver.get("https://atid.store/");
			driver.manage().window().setSize(new Dimension(1052, 666));
			
			ContactUsPage contactUsPage = new ContactUsPage(driver);
			
			//driver.findElement(By.xpath("//*[@id=\"menu-item-829\"]/a")).click();
			contactUsPage.ClickContactUs();
			Thread.sleep(1000);
			contactUsPage.enterName((String) obj.get("name"));
			contactUsPage.enterSubject((String) obj.get("subject"));
			contactUsPage.enterEmail((String) obj.get("email"));
			contactUsPage.enterMessage((String) obj.get("message"));
			Thread.sleep(3000);
			contactUsPage.sendMessage();
		}

	}

	@Test
	public void UnsuccessfulMessageSent() throws InterruptedException {
		printMethodName();
		for (int i = 0; i < users.size(); i++) {
			JSONObject obj = (JSONObject) users.get(i);
			driver.get("https://atid.store/");
			driver.manage().window().setSize(new Dimension(1052, 666));
			ContactUsPage contactUsPage = new ContactUsPage(driver);
			contactUsPage.ClickContactUs();
			Thread.sleep(3000);
			contactUsPage.sendMessage();
			if(contactUsPage.isFoundErr()) {
				//Successful test
			}
			else {
				//Unsuccessful test
			}

		}
	
	}

	

	
	public static void main(String args[]) {
		JUnitCore junit = new JUnitCore();
		junit.addListener(new TextListener(System.out));
		org.junit.runner.Result result = junit.run(ContactUsTests.class);

		if (result.getFailureCount() > 0) {
			System.out.println("Test failed.");
			System.exit(1);
		} else {
			System.out.println("Test finished without errors.");
			// System.exit(0);
		}

		System.out.println("All tests finished successfully");
		System.exit(0);

	}
}