package tests;

import java.io.FileReader;
import java.io.IOException;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
//Generated by Selenium IDE
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.internal.TextListener;
import org.junit.runner.JUnitCore;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;

import pages.ContactUsPage;

public class ContactUsTests {
	private static WebDriver driver;
	private JSONArray users;
	Logger logger = LogManager.getLogger(ContactUsTests.class);

	JavascriptExecutor js;

	@Before

	public void setUp() throws IOException {
		driver = BaseTestClass.initializeDriver();
		js = (JavascriptExecutor) driver;

		try {
			JSONParser jsonParser = new JSONParser();
			FileReader reader;
			reader = new FileReader("ContactUsUsers.json");
			// Read JSON file
			users = (JSONArray) jsonParser.parse(reader);
		} catch (ParseException e) {
			e.printStackTrace();
		}

	}

	public static String getMethodName() {
		return Thread.currentThread().getStackTrace()[2].getMethodName();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void SuccessfulMessageSent() throws InterruptedException {
		logger.info("Starting " + getMethodName());
		for (int i = 0; i < users.size(); i++) {
			JSONObject obj = (JSONObject) users.get(i);
			logger.info("read object number " + (i+1) + " from json");
			driver.get("https://atid.store/");
			logger.info("opening website");
			driver.manage().window().setSize(new Dimension(1052, 666));
			logger.info("increase window size");
			ContactUsPage contactUsPage = new ContactUsPage(driver);
		
			contactUsPage.ClickContactUs();
			logger.debug("click on contact us");
			Thread.sleep(1000);
			contactUsPage.enterName((String) obj.get("name"));
			logger.debug("send name as key");
			contactUsPage.enterSubject((String) obj.get("subject"));
			logger.debug("send subject as key");
			contactUsPage.enterEmail((String) obj.get("email"));
			logger.debug("send email as key");
			contactUsPage.enterMessage((String) obj.get("message"));
			logger.debug("send message as key");
			Thread.sleep(3000);
			contactUsPage.sendMessage();
			logger.debug("click on send message");
			if(!contactUsPage.isFoundErr()) {
				//Successful test
				logger.info("Successful send message Operation test finished successfuly");
			}
			else {
				//Unsuccessful test
				logger.info("Successful send message Operation test finished with errors");
			}
		}

	}

	@Test
	public void UnsuccessfulMessageSent() throws InterruptedException {
		logger.info("Starting " + getMethodName());
		for (int i = 0; i < users.size(); i++) {
			driver.get("https://atid.store/");
			logger.info("opening website");
			driver.manage().window().setSize(new Dimension(1052, 666));
			logger.info("increase window size");
			ContactUsPage contactUsPage = new ContactUsPage(driver);
			contactUsPage.ClickContactUs();
			logger.debug("click on contact us");
			Thread.sleep(3000);
			contactUsPage.sendMessage();
			logger.debug("click on send message without sending keys");
			if(contactUsPage.isFoundErr()) {
				//Successful test
				logger.info("Unsuccessful send message Operation test finished successfuly");
			}
			else {
				//Unsuccessful test
				logger.error("Unsuccessful send message Operation test finished with errors");
			}
		}
	}


	public static void main(String args[]) {
		JUnitCore junit = new JUnitCore();
		junit.addListener(new TextListener(System.out));
		org.junit.runner.Result result = junit.run(ContactUsTests.class);
		if (result.getFailureCount() > 0) {
			System.out.println("Test failed.");
			System.exit(1);
		} else 
			System.out.println("Test finished without errors.");
		System.out.println("All tests finished successfully");
		System.exit(0);

	}
}